package com.ms.base.dataobject;

import java.util.Date;

public class PromoDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column promo_record.id
     *
     * @mbg.generated Wed Mar 25 23:04:56 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column promo_record.start_date
     *
     * @mbg.generated Wed Mar 25 23:04:56 CST 2020
     */
    private Date startDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column promo_record.item_id
     *
     * @mbg.generated Wed Mar 25 23:04:56 CST 2020
     */
    private Integer itemId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column promo_record.promo_item_price
     *
     * @mbg.generated Wed Mar 25 23:04:56 CST 2020
     */
    private Long promoItemPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column promo_record.promo_name
     *
     * @mbg.generated Wed Mar 25 23:04:56 CST 2020
     */
    private String promoName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column promo_record.end_date
     *
     * @mbg.generated Wed Mar 25 23:04:56 CST 2020
     */
    private Date endDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column promo_record.id
     *
     * @return the value of promo_record.id
     *
     * @mbg.generated Wed Mar 25 23:04:56 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column promo_record.id
     *
     * @param id the value for promo_record.id
     *
     * @mbg.generated Wed Mar 25 23:04:56 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column promo_record.start_date
     *
     * @return the value of promo_record.start_date
     *
     * @mbg.generated Wed Mar 25 23:04:56 CST 2020
     */
    public Date getStartDate() {
        return startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column promo_record.start_date
     *
     * @param startDate the value for promo_record.start_date
     *
     * @mbg.generated Wed Mar 25 23:04:56 CST 2020
     */
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column promo_record.item_id
     *
     * @return the value of promo_record.item_id
     *
     * @mbg.generated Wed Mar 25 23:04:56 CST 2020
     */
    public Integer getItemId() {
        return itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column promo_record.item_id
     *
     * @param itemId the value for promo_record.item_id
     *
     * @mbg.generated Wed Mar 25 23:04:56 CST 2020
     */
    public void setItemId(Integer itemId) {
        this.itemId = itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column promo_record.promo_item_price
     *
     * @return the value of promo_record.promo_item_price
     *
     * @mbg.generated Wed Mar 25 23:04:56 CST 2020
     */
    public Long getPromoItemPrice() {
        return promoItemPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column promo_record.promo_item_price
     *
     * @param promoItemPrice the value for promo_record.promo_item_price
     *
     * @mbg.generated Wed Mar 25 23:04:56 CST 2020
     */
    public void setPromoItemPrice(Long promoItemPrice) {
        this.promoItemPrice = promoItemPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column promo_record.promo_name
     *
     * @return the value of promo_record.promo_name
     *
     * @mbg.generated Wed Mar 25 23:04:56 CST 2020
     */
    public String getPromoName() {
        return promoName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column promo_record.promo_name
     *
     * @param promoName the value for promo_record.promo_name
     *
     * @mbg.generated Wed Mar 25 23:04:56 CST 2020
     */
    public void setPromoName(String promoName) {
        this.promoName = promoName == null ? null : promoName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column promo_record.end_date
     *
     * @return the value of promo_record.end_date
     *
     * @mbg.generated Wed Mar 25 23:04:56 CST 2020
     */
    public Date getEndDate() {
        return endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column promo_record.end_date
     *
     * @param endDate the value for promo_record.end_date
     *
     * @mbg.generated Wed Mar 25 23:04:56 CST 2020
     */
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }
}