package com.ms.base.dao;

import com.ms.base.dataobject.SequenceDO;

public interface SequenceDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_record
     *
     * @mbg.generated Sat Mar 21 18:40:03 CST 2020
     */
    int deleteByPrimaryKey(String name);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_record
     *
     * @mbg.generated Sat Mar 21 18:40:03 CST 2020
     */
    int insert(SequenceDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_record
     *
     * @mbg.generated Sat Mar 21 18:40:03 CST 2020
     */
    int insertSelective(SequenceDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_record
     *
     * @mbg.generated Sat Mar 21 18:40:03 CST 2020
     */
    SequenceDO selectByPrimaryKey(String name);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_record
     *
     * @mbg.generated Sat Mar 21 18:40:03 CST 2020
     */
    int updateByPrimaryKeySelective(SequenceDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_record
     *
     * @mbg.generated Sat Mar 21 18:40:03 CST 2020
     */
    int updateByPrimaryKey(SequenceDO record);

    SequenceDO selectByName(String name);

    int updateByName(String name, Integer step);
}